In [1]:
#importing the library
import pandas as pd

In [2]:
#creating the df from the csv file
data = pd.read_csv("weather_data.csv")
data

         day  temp condition
0     Monday    12     Sunny
1    Tuesday    14      Rain
2  Wednesday    15      Rain
3   Thursday    14    Cloudy
4     Friday    21     Sunny
5   Saturday    22     Sunny
6     Sunday    24     Sunny

In [7]:
#cheking the type 
type(data)

pandas.core.frame.DataFrame

In [13]:
#exploring functionality:
#1.converting it to a dictionary
data_dict = data.to_dict()
data_dict

{'day': {0: 'Monday',
  1: 'Tuesday',
  2: 'Wednesday',
  3: 'Thursday',
  4: 'Friday',
  5: 'Saturday',
  6: 'Sunday'},
 'temp': {0: 12, 1: 14, 2: 15, 3: 14, 4: 21, 5: 22, 6: 24},
 'condition': {0: 'Sunny',
  1: 'Rain',
  2: 'Rain',
  3: 'Cloudy',
  4: 'Sunny',
  5: 'Sunny',
  6: 'Sunny'}}

In [14]:
#2.converting a column to a list
data_temp = data['temp'].to_list()
data_temp

[12, 14, 15, 14, 21, 22, 24]

In [18]:
#3.getting the average of a column
avg_data_temp = data['temp'].mean()
round(avg_data_temp,2)

17.43

In [19]:
#4.getting the max value of a column
max_temp = data['temp'].max()
max_temp

24

In [20]:
#5.getting descriptive stats about the df
data.describe()

            temp
count   7.000000
mean   17.428571
std     4.755949
min    12.000000
25%    14.000000
50%    15.000000
75%    21.500000
max    24.000000

In [24]:
#accessing a row in the df
data[data['day'] == 'Monday']

#very wierd, but just accept it
#think of it like this: from the data df, from the column titled 'day', get the row info for the entry 'Monday'

      day  temp condition
0  Monday    12     Sunny

In [25]:
#adding some functionality to get the row
data[data['temp'] == data['temp'].max()]

#getting the row with the max temprature.

      day  temp condition
6  Sunday    24     Sunny

In [27]:
monday = data[data['day'] == 'Monday']
monday

      day  temp condition
0  Monday    12     Sunny

In [33]:
#converting celcius to farenheit
temp = monday['temp']
new_temp = temp * 9/5 +32
new_temp

0    53.6
Name: temp, dtype: float64

In [43]:
#create a df from a dictionary
products = {
    'Jeans': 49.99,
    'T-Shirt': 14.99,
    'Suit': 89.99
}

new_data = pd.DataFrame(products,index=[0])
new_data

   Jeans  T-Shirt   Suit
0  49.99    14.99  89.99